### ISSUE TITLE
Delete temp folder after dowloading the textures

### ISSUE THREAD

**Issue by cerus** [cerus/visual-crafting#1]
This is a very easy fix. The plugin is not deleting the `plugins/visual-crafting/temp` folder after it finished downloading and converting the textures. We don't need that folder, so we can delete it when we're done.

There's a little bug in the downloader code: The `folder.delete()` call is outside of the executor runnable. At the moment the folder is created, then immediately deleted and then created again. That's not really how it should work; The `.delete()` call should be moved to the bottom of the executor runnable. Bonus points if you also delete the folder when the downloader encounters an exception.

Relevant code:
https://github.com/cerus/visual-crafting/blob/main/plugin/src/main/java/dev/cerus/visualcrafting/plugin/texture/TextureDownloader.java#L109

Please comment if you would like to work on this and don't forget to follow the [contribution guidelines](https://github.com/cerus/visual-crafting/blob/main/CONTRIBUTING.md).

**Comment by Jupiops** [comment]
I would like to work on this

**Comment by cerus** [comment]
Alrighty, I've assigned the issue to you @Jupiops! I'm not sure if you're familiar with [Hacktoberfest](https://hacktoberfest.com/), but if you want you can wait until October 1st before submitting your pull request.

**Comment by Jupiops** [comment]
Short question regarding the folder: Can I expect the folder to always be empty at the end of the executor runnable? Because otherwise the `folder.delete()` call would fail with and `IOException`.

**Comment by cerus** [comment]
Yeah, expect it to be empty. But if you want you can add a little sanity check (something like `if(folder.listFiles().length == 0) {...}`
